export enum FoundSupportNotificationStrategy {
  SECURITY_NOTICE = 'SECURITY_NOTICE',
  PICKUP_AVAILABLE = 'PICKUP_AVAILABLE',
  LEGAL_GUARDIAN_OR_PAYER = 'LEGAL_GUARDIAN_OR_PAYER',
  REVIEW_BEFORE_NOTIFICATION = 'REVIEW_BEFORE_NOTIFICATION',
  SUPPORT_UNUSABLE_NOTICE = 'SUPPORT_UNUSABLE_NOTICE',
  UNKNOWN_SUPPORT_NO_NOTIFICATION = 'UNKNOWN_SUPPORT_NO_NOTIFICATION',
}
