export enum FoundSupportDecision {
  FOUND_PICKUP_ALLOWED = 'FOUND_PICKUP_ALLOWED',
  CONTROLLED_REUSE_ELIGIBLE = 'CONTROLLED_REUSE_ELIGIBLE',
  BACKOFFICE_REVIEW_REQUIRED = 'BACKOFFICE_REVIEW_REQUIRED',
  SUPPORT_ALREADY_REPLACED = 'SUPPORT_ALREADY_REPLACED',
  SUPPORT_UNUSABLE = 'SUPPORT_UNUSABLE',
  UNKNOWN_SUPPORT = 'UNKNOWN_SUPPORT',
}
